name: Deploy to VPS

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    # Appel au workflow de test
    tests:
        uses: ./.github/workflows/test.yml

    # Appel au workflow de construction
    build:
        uses: ./.github/workflows/build.yml
        needs: tests
        
    # Déploiement de l'application
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Copy configuration files to VPS
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  source: "docker-compose.yml,scripts/deploy.sh"
                  target: "~/techno-scraper"
                  overwrite: true

            - name: Configure environment and deploy
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  envs: API_KEY,GITHUB_TOKEN,GITHUB_ACTOR,GITHUB_REPOSITORY
                  script: |
                      # Aller dans le répertoire du projet
                      cd ~/techno-scraper

                      # Créer ou mettre à jour le fichier .env
                      cat > .env << EOL
                      # Configuration de l'application
                      DEBUG=False
                      API_KEY=${{ secrets.API_KEY }}

                      # Configuration du serveur
                      HOST=0.0.0.0
                      PORT=8000

                      # Configuration des logs
                      LOG_LEVEL=INFO

                      # Configuration des retries
                      MAX_RETRIES=3
                      RETRY_BACKOFF_FACTOR=0.5
                      REQUEST_TIMEOUT=30

                      # User-Agent (optionnel, "random" pour générer aléatoirement)
                      USER_AGENT=random
                      EOL

                      # Rendre le script de déploiement exécutable
                      chmod +x scripts/deploy.sh
                      
                      # Définir les variables pour le script de déploiement
                      export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
                      export GITHUB_ACTOR=${{ github.actor }}
                      export GITHUB_REPOSITORY=${{ github.repository }}
                      
                      # Exécuter le script de déploiement
                      ./scripts/deploy.sh
