name: Manual Test Run

on:
  workflow_dispatch:
    inputs:
      coverage_report:
        description: 'Générer un rapport de couverture détaillé'
        required: false
        default: false
        type: boolean
      python-version:
        description: 'Version de Python à utiliser'
        required: false
        default: '3.13'
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python Environment
        uses: ./.github/actions/setup-python
        with:
          python-version: ${{ inputs.python-version }}
          install-test-deps: 'true'
            
      - name: Run tests
        run: |
            pytest -v --cov=app tests/
            
      - name: Generate detailed coverage report
        if: ${{ inputs.coverage_report == true }}
        run: |
            pytest --cov=app --cov-report=html tests/
            
      - name: Archive coverage report
        if: ${{ inputs.coverage_report == true }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/
          retention-days: 5 