name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:
    # Permet à ce workflow d'être appelé par d'autres workflows

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python Environment
        uses: ./.github/actions/setup-python
        with:
          python-version: '3.13'
          install-test-deps: 'true'
            
      - name: Run tests
        run: |
            pytest -v --cov=app tests/
            
      - name: Generate coverage report
        run: |
            pytest --cov=app --cov-report=xml tests/
            
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
            file: ./coverage.xml
            fail_ci_if_error: false 